services:
  nestjs-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: nestjs-app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgresDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
